routes/web.php
		Route::get('/skills/gallery/slide/image','SkillController@skillGallerySlideImages')->name('skillslidergallery.images');
		Route::get('/skills/view/gallery/{id}','SkillController@viewGallery')->name('view.skillgallery');
		Route::get('/skills/video/show','SkillController@videoShow')->name('skill.video.show');

		Route::post('/skills/addtag','SkillController@addTag')->name('skill.addtag');
		Route::get('/skills/removetag','SkillController@removeTag')->name('skill.removetag');
		Route::post('/skills/add/video','SkillController@addSkillVideo')->name('add.skills.video');
		Route::post('/skillGalleryUpdate','SkillController@skillGalleryUpdate')->name('skillGalleryUpdate');
		Route::get('/skills/removemedia','SkillController@removeSkillMedia')->name('skills.removeMedia');	

		Route::get('/skills/search','SkillController@skillsSearch')->name('skills.search');
		Route::get('/skills/getTags','SkillController@getTags')->name('skills.getTags');
		
 
		Route::post('storeprofile','PortfolioController@storeprofile')->name('storeprofile');

		Route::post('changepassword','PortfolioController@changePassword')->name('changepassword');

 		Route::post('/rental/images','RentalController@storeRentalImages')->name('store.rental.images');
		Route::post('/rental/media','RentalController@storeRantalMedia')->name('store.rental.media');
		Route::post('/rental/addtag','RentalController@rentalAddTag')->name('rental.addtag');

		Route::get('/rental/removetag','RentalController@removeRentalTag')->name('rental.removetag');

		Route::get('/rental/removemedia','RentalController@removeRentalMedia')->name('rental.removeMedia');

		Route::post('/rental/add/images','RentalController@addRentalImages')->name('add.rental.images');

		Route::get('/rental/search','RentalController@rentalSearch')->name('rental.search');
		Route::get('/rental/gallery/slide/image','RentalController@rentalGallerySlideImages')->name('rentalslidergallery.images');
		Route::post('/rentalGalleryUpdate','RentalController@rentalGalleryUpdate')->name('rentalGalleryUpdate');
		Route::get('/rental/getTags','RentalController@getTags')->name('rental.getTags');
	
		Route::get('/rental/view/gallery/{id}','RentalController@viewGallery')->name('view.rentalgallery');

		Route::post('/rentalGalleryremove','RentalController@rentalGalleryRemove')->name('rentalGalleryRemove');

 		Route::get('/projectdata','ResumeController@projectdata')->name('projectdata');
		Route::get('/addworktitle','ResumeController@addworktitle')->name('addworktitle');
		Route::get('/addimdc','ResumeController@addimdc')->name('addimdc');
		Route::get('/roleDelete','ResumeController@roleDelete')->name('roleDelete');
		Route::get('/addrole','ResumeController@addrole')->name('addrole');
		Route::get('/updateRole','ResumeController@updateRole')->name('updateRole');
		Route::get('/addprojecttitle','ResumeController@addprojecttitle')->name('addprojecttitle');
		Route::get('/deleteProject','ResumeController@deleteProject')->name('deleteProject');
		Route::get('/editResume','ResumeController@editResume')->name('editResume');
		Route::get('/resumeSearch','ResumeController@resumeSearch')->name('resumeSearch');
		
		

 
		Route::get('/addrestriction','RestrictionController@addrestriction')->name('addrestriction');
		Route::get('/addnudity','RestrictionController@addnudity')->name('addnudity');

 		

 });



/** end route performers **/


/****************   InternalStaff Authentication ************************/

//Route::group(['domain' => 'talent.freemancasting.com','namespace'=>'InternalStaff','as'=>'internal-staff.'],function(){
Route::group(['prefix' => 'internal-staff','namespace'=>'InternalStaff','as'=>'internal-staff.'],function(){	
	Route::get('/','InternalStaffController@index')->name('internal-staff');
	Route::group(['namespace'=>'Auth'],function(){
		// Route::get('internal-staff/register', 'RegisterController@showRegistrationForm')->name('register');
		// Route::post('internal-staff/register', 'RegisterController@register')->name('signup');
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});
	
	
	/** AUTH IN INTERNAL STAFF **/
	Route::group(['middleware' => ['auth:internal-staff']],function(){
		Route::get('/','InternalStaffController@performersList')->name('performers.list');
		Route::get('performers/list','InternalStaffController@performersList')->name('performers.list');
		Route::get('add','InternalStaffController@add')->name('add');
		Route::get('performers/detail','InternalStaffController@performersDetail')->name('performers.detail');
		
		/** SCROLL **/
		Route::get('/performersScroll','InternalStaffController@performersScroll')->name('performersScroll');
		Route::get('/performersScrollSearch','SearchController@searchScroll')->name('performersScrollSearch');
		Route::get('/myperformers','InternalStaffController@myperformers')->name('myperformers');

		//list view
		Route::post('/saveflag','InternalStaffController@saveFlag')->name('saveFlag');
		Route::get('/listview','InternalStaffController@listView')->name('listview');

		Route::post('/removeflag','InternalStaffController@removeFlag')->name('removeflag');

		Route::post('/save/result','SearchController@searchResultSave')->name('search.result');		
		Route::get('/search/result/{id}','SearchController@SearchResultDisplay')->name('search.result.display');		

		Route::get('/search','SearchController@search')->name('search');
		Route::get('/search/selectoption','SearchController@searchSelectOption')->name('searchSelectOption');
		Route::get('/portfolio/getSliderImage','InternalStaffController@getSliderImage')->name('portfolio.getSliderImage');
		Route::get('/search/advanceselect','SearchController@advanceSearch')->name('advanceSearch');
		//internal profile Update 
		Route::post('/update/profile','InternalStaffController@updateProfile')->name('updateProfile');
		Route::post('changepassword','InternalStaffController@changePassword')->name('changepassword');
		Route::post('addperformer','InternalStaffController@addperformer')->name('addperformer');
		Route::get('/projectdata','ResumeController@projectdata')->name('projectdata');
Route::get('/savenotes','InternalStaffController@savenotes')->name('savenotes');
		Route::get('/deletenote','InternalStaffController@deletenote')->name('deletenote');
		Route::get('/editnote','InternalStaffController@editnote')->name('editnote');
		Route::get('/updatenote','InternalStaffController@updatenote')->name('updatenote');

	});


	/** END AUTH IN INTERNAL STAFF **/

});

/****************  InternalStaff Authentication ************************/


/****************   Corporate Admin Authentication ************************/

Route::group(['prefix' => 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
//Route::group(['domain' => 'talent.freemancasting.com','prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
	
	Route::get('/','CorporateAdminController@index')->name('corporate-admin');

	Route::group(['namespace'=>'Auth'],function(){


		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});



});
//Route::group(['prefix'=> 'corporate-admin','domain' => 'talent.freemancasting.com','namespace'=>'CorporateAdmin' ,'as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){

Route::group(['prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){
	Route::get('/form','CorporateAdminController@form')->name('form');
	Route::post('/addstaff','CorporateAdminController@store')->name('addstaff');
	Route::get('list','CorporateAdminController@list')->name('list'); 
	Route::get('edit/{id}','CorporateAdminController@edit')->name('edit');
	Route::post('store','CorporateAdminController@save')->name('store');
	Route::get('delete','CorporateAdminController@delete')->name('delete');	
	Route::get('status/{id}','CorporateAdminController@status')->name('status');
	Route::get('skintone','CorporateAdminController@tone')->name('skintone');	
	Route::get('eyes','CorporateAdminController@eyes')->name('eyes');	
	Route::get('availability','CorporateAdminController@Availability')->name('availability');	
	Route::get('performerstatus','CorporateAdminController@performerStatus')->name('performerstatus');	
		
	Route::get('documents','CorporateAdminController@documents')->name('documents');	
	Route::get('piercing','CorporateAdminController@piercing')->name('piercing');	
	Route::get('tattoo','CorporateAdminController@tattoo')->name('tattoo');	
	Route::get('helpdesk','CorporateAdminController@helpdesk')->name('helpdesk');	
	
	Route::get('haircolor','CorporateAdminController@haircolor')->name('haircolor');
	
	//hair facial list

	Route::get('hairfacial','CorporateAdminController@hairfacial')->name('hairfacial');	
	
	//hair Style list

app/Models/v1/InternalStaff.php
<?php

namespace App\Models\v1;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\InternalStaffResetPasswordnotification;

class InternalStaff extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   protected $table  = 'internal_staffs';
    protected $guard = 'internal-staff';
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new InternalStaffResetPasswordnotification($token));
    }
    protected $fillable = [
        'lastname',
        'firstname',
        'email',
        'phonenumber',
        'password',
         'status',
        'remember_token',
        'created_at',
        'updated_at'  
    ];
    protected $appends  =[
        'full_name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
      function getFullNameAttribute() {
          return $this->firstname . ' ' . $this->lastname;
    }
}

resources/views/internal-staff/index.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel performers 123</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">
            @if (Route::has('login'))
                <div class="top-right links">
                    @if(Auth::guard('internal-staff')->check())
                        <a href="{{ url('/home') }}">Home</a>
                        <a href="{{ route('internal-staff.logout') }}" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            LOG OUT
                        </a>
                        <form id="logout-form" action="{{ route('internal-staff.logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    @else
                        <a href="{{ route('internal-staff.login') }}">Login</a>
                    @endif
                </div>
            @endif

            <div class="content">
                <div class="title m-b-md">
                    Laravel performers
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Docs</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://blog.laravel.com">Blog</a>
                    <a href="https://nova.laravel.com">Nova</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
            </div>
        </div>
    </body>
</html>

resources/views/internal-staff/listview.blade.php
@extends('internal-staff.layouts.app')
@section('content')

<div class="listviewpagedeta">
	<div class="serboxtitlebox">
	    <div class="serboxtitle_boxleft">
	        <h3>Freeman Casting</h3>
	    </div>
	    <div class="serboxtitle_boxright">
	        <div class="showboxart">
	            <a href="javascript:void(0)">Show: <span>30</span> <i class="far fa-sort"></i></a>
	        </div>
	        <div class="layoutsbtncng">
	            <p>Layout:</p>
	            <a href="javascript:void(0)" class="active"><i class="far fa-grip-horizontal"></i></a>
	            <a href="javascript:void(0)"><i class="far fa-list"></i></a>
	        </div>
	    </div>
	</div>

	<div class="litboxldetabox">
		<div class="fremanctlistbox">
			<div class="fremanctlistiner1">
				<img src="http://192.168.1.18/freemancasting/public/storage/performers/1/1563363531Chrysanthemum.jpg" alt="">
			</div>
			<div class="fremanctlistiner2">
				<h4>Pan Hyuk</h4>
				<p><span class="fagesp">33F</span> <span class="fagesp">5'8"</span> <span class="fagesp">99.8lbs</span></p>
			</div>
			<div class="fremanctlistiner3">
				<h5 class="blokedcol">Booked</h5>
				<p>UBCP Extra</p>
			</div>
			<div class="fremanctlistiner4">
				<h6>Profile last updated</h6>
				<p>15 Jan 2019</p>
			</div>
			<div class="fremanctlistiner5">				
				<div class="flggrnbox_left1">
	                <p>1</p>
	                <i class="far fa-flag-alt"></i>
	            </div>
	            <div class="flggrnbox_right1">
	                <p>U-123</p> <p>GRE</p>
	            </div>
			</div>
			<div class="fremanctlistiner6">
				<a href="javascript:void(0)">View Profile</a>
			</div>
		</div>
		<div class="fremanctlistbox">
			<div class="fremanctlistiner1">
				<img src="http://192.168.1.18/freemancasting/public/storage/performers/1/1563363531Chrysanthemum.jpg" alt="">
			</div>
			<div class="fremanctlistiner2">
				<h4>Pan Hyuk</h4>
				<p><span class="fagesp">33F</span> <span class="fagesp">5'8"</span> <span class="fagesp">99.8lbs</span></p>
			</div>
			<div class="fremanctlistiner3">
				<h5 class="onholdcol">1st Hold</h5>
				<p>UBCP Extra</p>
			</div>
			<div class="fremanctlistiner4">
				<h6>Profile last updated</h6>
				<p>15 Jan 2019</p>
			</div>
			<div class="fremanctlistiner5">				
				<div class="flggrnbox_left1">
	                <p>1</p>
	                <i class="far fa-flag-alt"></i>
	            </div>
	            <div class="flggrnbox_right1">
	                <p>U-123</p> <p>GRE</p>
	            </div>
			</div>
			<div class="fremanctlistiner6">
				<a href="javascript:void(0)">View Profile</a>
			</div>
		</div>
		<div class="fremanctlistbox">
			<div class="fremanctlistiner1">
				<img src="http://192.168.1.18/freemancasting/public/storage/performers/1/1563363531Chrysanthemum.jpg" alt="">
			</div>
			<div class="fremanctlistiner2">
				<h4>Pan Hyuk</h4>
				<p><span class="fagesp">33F</span> <span class="fagesp">5'8"</span> <span class="fagesp">99.8lbs</span></p>
			</div>
			<div class="fremanctlistiner3">
				<h5 class="notavailablecol">Not Available</h5>
				<p>UBCP Extra</p>
			</div>
			<div class="fremanctlistiner4">
				<h6>Profile last updated</h6>
				<p>15 Jan 2019</p>
			</div>
			<div class="fremanctlistiner5">				
				<div class="flggrnbox_left1">
	                <p>1</p>
	                <i class="far fa-flag-alt"></i>
	            </div>
	            <div class="flggrnbox_right1">
	                <p>U-123</p> <p>GRE</p>
	            </div>
			</div>
			<div class="fremanctlistiner6">
				<a href="javascript:void(0)">View Profile</a>
			</div>
		</div>

	</div>
</div>

@endsection

resources/views/internal-staff/myperfomers.blade.php
@extends('internal-staff.layouts.app')
@section('content')
<div class="databaseboxalldeta">

  <div class="perfotblboxdis">
    <h3>My Performers</h3>
    <table class="table table-bordered notestblbox" id="saveperformers" >
      <thead>
        <tr>
          <th class="text-center">ID</th>
          <th class="text-center">Title</th>
          <th class="text-center">Date</th>
          <th class="text-center">Action</th>
        </tr>
      </thead>
      <tbody>
        @if(count($searchResult))
        @foreach($searchResult as $key=>$value)
        <tr>
          <td>{{$key+=1}}</td>
          <td>{{$value->my_performer}}</td>
          <td>{{$value->created_at->setTimezone(Auth::user()->timezone)->format('m/d/Y H:i:s')}}</td>
          <td><a href="{{route('internal-staff.search.result.display',['id'=>$value->id])}}"><i class="far fa-eye"></i></a></td>
        </tr>
        @endforeach
        @endif

      </tbody>
    </table>
  </div>

</div>
@endsection
@section('scripts')
<script type="text/javascript">
  
$('#saveperformers').DataTable({
    "order": [[ 3, "desc" ]]
  });
</script>

@endsection

resources/views/internal-staff/performerpasswordreset.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<h1>Credential Details</h1>
	<label>Email :</label> {{$email}}<br>
	<label>Password :</label> {{$password}}<br>
	<a href="https://talent.freemancasting.com/login">Click here to login into Internal staff</a>

</body>
</html>