routes/web.php
		// Route::get('internal-staff/register', 'RegisterController@showRegistrationForm')->name('register');
		// Route::post('internal-staff/register', 'RegisterController@register')->name('signup');
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});
	
	
	/** AUTH IN INTERNAL STAFF **/
	Route::group(['middleware' => ['auth:internal-staff']],function(){
		Route::get('/','InternalStaffController@performersList')->name('performers.list');
		Route::get('performers/list','InternalStaffController@performersList')->name('performers.list');
		Route::get('add','InternalStaffController@add')->name('add');
		Route::get('performers/detail','InternalStaffController@performersDetail')->name('performers.detail');
		
		/** SCROLL **/
		Route::get('/performersScroll','InternalStaffController@performersScroll')->name('performersScroll');
		Route::get('/performersScrollSearch','SearchController@searchScroll')->name('performersScrollSearch');
		Route::get('/myperformers','InternalStaffController@myperformers')->name('myperformers');

		//list view
		Route::post('/saveflag','InternalStaffController@saveFlag')->name('saveFlag');
		Route::get('/listview','InternalStaffController@listView')->name('listview');

		Route::post('/removeflag','InternalStaffController@removeFlag')->name('removeflag');

		Route::post('/save/result','SearchController@searchResultSave')->name('search.result');		
		Route::get('/search/result/{id}','SearchController@SearchResultDisplay')->name('search.result.display');		

		Route::get('/search','SearchController@search')->name('search');
		Route::get('/search/selectoption','SearchController@searchSelectOption')->name('searchSelectOption');
		Route::get('/portfolio/getSliderImage','InternalStaffController@getSliderImage')->name('portfolio.getSliderImage');
		Route::get('/search/advanceselect','SearchController@advanceSearch')->name('advanceSearch');
		//internal profile Update 
		Route::post('/update/profile','InternalStaffController@updateProfile')->name('updateProfile');
		Route::post('changepassword','InternalStaffController@changePassword')->name('changepassword');
		Route::post('addperformer','InternalStaffController@addperformer')->name('addperformer');
		Route::get('/projectdata','ResumeController@projectdata')->name('projectdata');
Route::get('/savenotes','InternalStaffController@savenotes')->name('savenotes');
		Route::get('/deletenote','InternalStaffController@deletenote')->name('deletenote');
		Route::get('/editnote','InternalStaffController@editnote')->name('editnote');
		Route::get('/updatenote','InternalStaffController@updatenote')->name('updatenote');

	});


	/** END AUTH IN INTERNAL STAFF **/

});

/****************  InternalStaff Authentication ************************/


/****************   Corporate Admin Authentication ************************/

Route::group(['prefix' => 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
//Route::group(['domain' => 'talent.freemancasting.com','prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
	
	Route::get('/','CorporateAdminController@index')->name('corporate-admin');

	Route::group(['namespace'=>'Auth'],function(){


		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});



});
//Route::group(['prefix'=> 'corporate-admin','domain' => 'talent.freemancasting.com','namespace'=>'CorporateAdmin' ,'as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){

Route::group(['prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){
	Route::get('/form','CorporateAdminController@form')->name('form');
	Route::post('/addstaff','CorporateAdminController@store')->name('addstaff');
	Route::get('list','CorporateAdminController@list')->name('list'); 
	Route::get('edit/{id}','CorporateAdminController@edit')->name('edit');
	Route::post('store','CorporateAdminController@save')->name('store');
	Route::get('delete','CorporateAdminController@delete')->name('delete');	
	Route::get('status/{id}','CorporateAdminController@status')->name('status');
	Route::get('skintone','CorporateAdminController@tone')->name('skintone');	
	Route::get('eyes','CorporateAdminController@eyes')->name('eyes');	
	Route::get('availability','CorporateAdminController@Availability')->name('availability');	
	Route::get('performerstatus','CorporateAdminController@performerStatus')->name('performerstatus');	
		
	Route::get('documents','CorporateAdminController@documents')->name('documents');	
	Route::get('piercing','CorporateAdminController@piercing')->name('piercing');	
	Route::get('tattoo','CorporateAdminController@tattoo')->name('tattoo');	
	Route::get('helpdesk','CorporateAdminController@helpdesk')->name('helpdesk');	
	
	Route::get('haircolor','CorporateAdminController@haircolor')->name('haircolor');
	
	//hair facial list

	Route::get('hairfacial','CorporateAdminController@hairfacial')->name('hairfacial');	
	
	//hair Style list

	Route::get('hairstyle','CorporateAdminController@hairstyle')->name('hairstyle');	
	
	//Body Trait list

	Route::get('bodytrait','CorporateAdminController@bodytrait')->name('bodytrait');	
	
	Route::get('ethnicity','CorporateAdminController@ethnicity')->name('ethnicity');	
	Route::get('nationality','CorporateAdminController@nationality')->name('nationality');	
	Route::get('handedness','CorporateAdminController@handedness')->name('handedness');	
		
	Route::get('agent','CorporateAdminController@Agent')->name('agent');	
	Route::get('agency','CorporateAdminController@Agency')->name('agency');	
	Route::get('union','CorporateAdminController@Union')->name('Union');	
	Route::get('flag','CorporateAdminController@Flag')->name('Flag');	
	Route::get('hairlength','CorporateAdminController@hairlength')->name('hairlength');	
	Route::get('vehicle_type','CorporateAdminController@vehicletype')->name('vehicletype');
	Route::get('vehicle_year','CorporateAdminController@vehicleyear')->name('vehicleyear');
	Route::get('vehicle_make','CorporateAdminController@vehiclemake')->name('vehiclemake');
	Route::get('vehicle_model','CorporateAdminController@vehiclemodel')->name('vehiclemodel');
	Route::get('vehicle_condition','CorporateAdminController@vehiclecondition')->name('vehiclecondition');
	Route::get('vehicle_accessories','CorporateAdminController@vehicleaccessories')->name('vehicleaccessories');
	Route::post('addtone','CorporateAdminController@addtone')->name('addtone');
	Route::post('addeyes','CorporateAdminController@addeyes')->name('addeyes');
	Route::post('addpiercing','CorporateAdminController@addPiercing')->name('addpiercing');
	Route::post('addtattoo','CorporateAdminController@addTattoo')->name('addtattoo');
	Route::post('addunion','CorporateAdminController@addunion')->name('addunion');
	Route::post('addagent','CorporateAdminController@addagent')->name('addagent');
	Route::post('addagency','CorporateAdminController@addAgency')->name('addagency');
	Route::post('addflag','CorporateAdminController@addflag')->name('addflag');
	Route::post('addhelpdesk','CorporateAdminController@addhelpdesk')->name('addhelpdesk');
	Route::post('addvehicle_type','CorporateAdminController@addvehicletype')->name('addvehicletype');
	Route::post('addvehicle_make','CorporateAdminController@addvehiclemake')->name('addvehiclemake');
	Route::post('addvehicle_accessories','CorporateAdminController@addvehicleaccessories')->name('addvehicleaccessories');

	Route::post('adddocument','CorporateAdminController@adddocument')->name('adddocument');
	Route::post('addavailability','CorporateAdminController@addavailability')->name('addavailability');
	Route::post('addstatus','CorporateAdminController@addstatus')->name('addstatus');
	Route::post('addtag','CorporateAdminController@addtag')->name('addtag');
	Route::post('addhaircolor','CorporateAdminController@addhaircolor')->name('addhaircolor');
	Route::post('addnationality','CorporateAdminController@addnationality')->name('addnationality');
	Route::post('addethnicity','CorporateAdminController@addethnicity')->name('addethnicity');
	Route::post('addhandedness','CorporateAdminController@addhandedness')->name('addhandedness');
	Route::post('addhairlength','CorporateAdminController@addhairlength')->name('addhairlength');
	Route::post('addhairfacial','CorporateAdminController@addhairfacial')->name('addhairfacial');
	Route::post('addhairstyle','CorporateAdminController@addhairstyle')->name('addhairstyle');
	Route::post('addbodytrait','CorporateAdminController@addbodytrait')->name('addbodytrait');
	Route::post('updatetone','CorporateAdminController@updatetone')->name('updatetone');
	Route::post('updateethnicity','CorporateAdminController@updateethnicity')->name('updateethnicity');
	Route::post('updateeyes','CorporateAdminController@updateeyes')->name('updateeyes');

app/Models/v1/CorporateAdmin.php
<?php

namespace App\Models\v1;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\CorporateAdminResetPasswordNotification;

class CorporateAdmin extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   protected $table  = 'corporate_admins';
   protected $guard = 'corporate-admin';

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new CorporateAdminResetPasswordNotification($token));
    }
    
    protected $fillable = [
        'name',
        'email',
        'phonenumber',
        'password',
        'remember_token',
        'created_at',
        'updated_at'  
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

 

app/Http/Controllers/CorporateAdmin/document.php
@extends('performers.layouts.app')
@section('content')
<div class="wctleftrightbox">
  @if($performer->applicationfor == "Group")
  @include('performers.layouts.groupSidebar')  
  @else
  @include('performers.layouts.sidebar')  
  @endif
     <div class="rightallditinwct">
   <!--  <div class="searchbarboxfilt">
      <div class="srchbox">        
        <div class="form-group">
          <i class="far fa-search"></i>
          <input type="text" class="form-control" id="skillSearch" placeholder="Search">
        </div>
      </div>
      <div class="addandtagbox">
        <div class="addatribut">
          <a href="javascript:void(0)" type="button" data-toggle="modal" data-target="#myDocumentsModal"><i class="far fa-plus"></i>New Document</a>
        </div>
        <div class="tagboxright">
          <a href="javascript:void(0)"><i class="far fa-tag"></i></a>
        </div>
      </div>
    </div> -->
    <div class="addflagshidbox">
      <div class="accordion-container">
        <div class="set hedtobox">
          <div class="srchbox hidden">        
            <div class="form-group">
              <i class="far fa-search"></i>
             <input type="text" class="form-control" id="" placeholder="Search">
            </div>
          </div>
      @if($authtype=='performer')     
     @else
     @include('performers.flag')
     @endif       
        </div>      
      </div>
    </div>
  <div class="topbarbotdivcover">
    @if($authtype=='performer')
    @include('performers.layouts.tabbar')
    @else
    @include('performers.layouts.internal-tabbar')
    @endif
  
    <div class="doctslistdit">
      <div class="doctslistdit_title">

        <h3>Documents List</h3>
      </div>
      <div class="errbrtext">
        <i class="far fa-info-circle"></i>
        <p>Please be sure to store these documents in an easy to find locations so that you can bring them to set. You will not be able to work without these documents. Do not upload them to this system in any capacity.</p>
      </div>
      <div class="dpnpiwsbox">
        <div class="dpnpiwsbox_partdiv">
       @foreach($document as $doc)
        
          <div class="dpnpiwsbox_inerfullw">
            <div class="lefttextdpmpiws">
              <p>{{ $doc->doument_name }}</p>
            </div>
     <!--        <div class="righttextdpmpiws">  
              <div class="custheckedbox Checkedgrn">
                <input class="styled-checkbox documentcheckbox" id="{{$doc->id}}" type="checkbox" value="{{$doc->id}}" checked>
                <label for="{{$doc->id}}">Checked</label>
              </div>
              <div class="custheckedbox Checkedred">
                <input class="styled-checkbox documentcheckbox" id="{{$doc->id}}" type="checkbox" value="{{$doc->id}}">
                <label for="{{$doc->id}}">Not Checked</label>
              </div>
            </div> -->
          </div>  
          
           
          @endforeach
         
        </div>
        <div class="dpnpiwsbox_partdiv">
          @foreach($documentna as $nadoc)
          <div class="dpnpiwsbox_inerfullw">
            <div class="lefttextdpmpiws">
              <p>{{ $nadoc->doument_name }}</p>
            </div>
            <div class="righttextdpmpiws">
              <div class="notaplibox"><i class="far fa-minus-square"></i> <p> Not applicable</p></div>
            </div>
          </div>
          @endforeach          
        
        </div>



      </div>
      

  </div>
  
</div>

  
</div>
</div>
</div>



@endsection
@section('scripts')
<script type="text/javascript">
    $('.documentcheckbox').on('change', function(){ 
        id=$(this).attr('id');
        if (this.checked) {
             $.ajax({

                type: "POST",
                url: "{{route('performers.adddocument')}}",
                headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
                data: {
                        id:id
                      },
                success: function (data) {
                       // console.log(data);
                       toastr.success(data.message);
                      }         
            });
        }
        else{
           $.ajax({

              type: "POST",
              url: "{{route('performers.removedocument')}}",
              headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
              data: {
                      id:id
                    },
              success: function (data) {
                       toastr.success(data.message); 
                    }         
          });         
        }
    });
</script>
@include('performers.commonSkill')
@endsection

resources/views/corporate-admin/agency.blade.php
@extends('corporate-admin.layouts.app')
@section('content')
			<div class="users_datatablebox">
	      <div class="signeup_topbox">
	        <div class="signeup_lefttextbox">
	          <p>Agency</p>
	        </div>
	        <div class="addmemberbtn"> <a href="javascript:void(0)" id="openModel" data-toggle="modal" data-target="#AgencyModal" class="btn">Add Agency</a></div>
	      </div>

	      <table class="table table-striped table-hover datatables tablestaffint" style="width: 100%;" id="statstable">
	        <thead>
	          <tr>
	            <th>Sr</th>
	            <th>Agency Name</th>
              <th>Agency Abbreviation</th>
	            <th>Disable ?</th>
	            <th>Action</th>
	          </tr>
	        </thead>
	            <tbody>
	              <?php $i=1; ?>
	              @foreach($agency as $agen)
	              <tr>
	                <th><?php echo $i++; ?></th>
	                <th>{{$agen->agencyName}}</th>
                  <th>{{$agen->agencyAbbreviation}}</th>
	                <th><a href="javascript:void(0)" class="deleteagency editdeletebtn" id="deleteagency"  data-id="{{$agen->id}}">
                   @if($agen->is_deleted == 1)
                     No
                   @else
                     Yes
                   @endif 
                  </a></th>
	                <th>
	                	<a href="#" class="editdeletebtn editagency"  data-id="{{$agen->id}}" data-toggle="modal" data-target="#editModal"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a> 
	                </th>
	                </th>
	              </tr>

	              @endforeach  
	            </tbody>
	          </table>
	        </div>  
	        <!--     Agency Modal -->
	        <div class="modal fade editskinboxmodal" id="AgencyModal" role="dialog">
	          <div class="modal-dialog">
	            <div class="modal-content">
	              <div class="modal-body">
	                <div class="editsktoboxcover">
	                  <form method="post" action="{{route('corporate-admin.addagent')}}" enctype="multipart/form-data" id="addagent">
	                    @csrf          
	                    <div class="titlandclobtn2">
	                      <h3>Add Agency</h3>
	                      <button type="button" class="close" data-dismiss="modal"><img src="{{url('public/assets/corporate-admin/svg/close-icon.svg')}}" alt=""></button>
	                    </div>
	                    <div class="enterskintonebox">
	                      <div class="form-group">
	                        <input type="text" class="form-control"  name="agencyName" placeholder="Enter Agency" id="addAgencyName">
	                      </div>
	                      <div class="form-group">
	                        <input type="text" class="form-control"  name="agencyAbbreviation" placeholder="Enter Abbreviation" id="addabbreviation">

	                      </div>
	                      <input type="button" name="" value="Add Agency" class="btn" id="saveAgency">
	                    
	                    </div>
	                  </form>
	                </div> 
	              </div>
	            </div>
	          </div>
	        </div>
	        <!--    Edit Agency Modal -->
	        <div class="modal fade editskinboxmodal" id="editModal" role="dialog">
	          <div class="modal-dialog">
	            <div class="modal-content">
	              <div class="modal-body">
	                <div class="editsktoboxcover">
	                  <form method="post" action="{{route('corporate-admin.updateagency')}}" enctype="multipart/form-data" id="updateagencyform">
	                    @csrf          
	                    <div class="titlandclobtn2">
	                      <h3>Edit Agency</h3>
	                      <button type="button" class="close" data-dismiss="modal"><img src="{{url('public/assets/corporate-admin/svg/close-icon.svg')}}" alt=""></button>
	                    </div>
	                    <div class="enterskintonebox">
	                      <div class="form-group">
	                      	<input type="hidden" name="id" id="editagencyid">
	                        <input type="text" class="form-control"  name="agencyName" placeholder="Enter Agency" id="editAgencyName">
	                      </div>
	                      <div class="form-group">
	                        <input type="text" class="form-control"  name="agencyAbbreviation" placeholder="Enter Abbreviation" id="editabbreviation">

	                      </div>
	                      <input type="button" name="" value="Update" class="btn" id="updateagency">
	                    
	                    </div>
	                  </form>
	                </div> 
	              </div>
	            </div>
	          </div>
	        </div>
@endsection
@section('scripts')  
<script type="text/javascript">
  $('#saveAgency').click(function(){
    
        $.ajax({

          type: "POST",
          url: "{{route('corporate-admin.addagency')}}",
          headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
          data: {
                  agencyName:$('#addAgencyName').val(),
                  agencyAbbreviation:$('#addabbreviation').val()
                },
          success: function (data) {
                 // console.log(data);
                 if(data.status==false){
                    toastr.error(data.message);
                 }
                 else{
                    toastr.success(data.message);
                    $('#AgencyModal').modal('hide'); 
                    location.reload();
                 }
                 
                 }         
      });
  });
</script>
<script type="text/javascript">
  $(document).on('click', '.editagency', function (e) {
  e.preventDefault();
  var id = $(this).data('id');
  
   $.ajax({
              type: "GET",
              url: "{{route('corporate-admin.editagency')}}",
              data: {id:id},
              success: function (data) {
                          $("#editAgencyName").val(data.agencyName);
                          $("#editabbreviation").val(data.agencyAbbreviation);
                          $("#editagencyid").val(id);
                  }         
          }); 

   });
</script>
<script type="text/javascript">
   $("#updateagency").click(function(e){
      e.preventDefault()
     var form = $("#updateagencyform");
       
     $.ajax({
         type: form.attr('method'),
         url: form.attr('action'),
         data: form.serialize(),
         success: function (data, status) {
              if(data.error){
                 return;
             }
              if(data.status == false){
                toastr.error(data.message);
              }
              else{
              $('#editModal').modal('hide');  // Your modal Id
              toastr.success(data.message);
              location.reload();
            }
         },
         error: function (result) {

         }
     });
     
  });
</script>
<script type="text/javascript">
  $(document).ready(function(){
  $('.deleteagency').click(function(){
              
              
                 var id = $(this).data('id');
                   
                    $.ajax({
                             type: "GET",
                             url: "{{route('corporate-admin.deleteagency')}}",
                             data: {id:id},
                             success: function (data) {
                                    toastr.success(data.message);
                                    location.reload();    
                                 }         
                         }); 
              
             });
  });
</script>
<script type="text/javascript">

  
  $('.deleteagency[data-toggle=confirmation]').confirmation({
           rootSelector: '[data-toggle=confirmation]',
           container: 'body',
           onConfirm: function() {
              var id = $(this).data('id');
                
                 $.ajax({
                          type: "GET",
                          url: "{{route('corporate-admin.deleteagency')}}",
                          data: {id:id},
                          success: function (data) {
                               
                                toastr.success("Agency Deleted Successfully");
                                location.reload();
                              }         
                      }); 
           },
         });
 
  

</script>
<script type="text/javascript">
  $('#statstable').on('page.dt', function() {
    setTimeout(
      function() {
       $('.deleteagency').click(function(){
                   
                   
                      var id = $(this).data('id');
                        
                         $.ajax({
                                  type: "GET",
                                  url: "{{route('corporate-admin.deleteagency')}}",
                                  data: {id:id},
                                  success: function (data) {
                                         toastr.success(data.message);
                                         location.reload();    
                                      }         
                              }); 
                   
                  });
      }, 500);
  });
 
</script>
<script type="text/javascript">
  $('#statstable').on('order.dt', function() {
    setTimeout(
      function() {
        $('.deleteagency').click(function(){
                    
                    
                       var id = $(this).data('id');
                         
                          $.ajax({
                                   type: "GET",
                                   url: "{{route('corporate-admin.deleteagency')}}",
                                   data: {id:id},
                                   success: function (data) {
                                          toastr.success(data.message);
                                          location.reload();    
                                       }         
                               }); 
                    
                   });
      }, 500);
  });
 
</script>
@endsection

resources/views/corporate-admin/list.blade.php
@extends('corporate-admin.layouts.app')
@section('content')
  
    <div class="users_datatablebox">
      <div class="signeup_topbox">
        <div class="signeup_lefttextbox">
          <p>Internal Staff</p>        
        </div>
        <div class="addmemberbtn"><a href="{{route('corporate-admin.form')}}" class="btn">Add Member</a></div>
      </div>
      

      <table class="table table-striped table-hover datatables tablestaffint" style="width: 100%;" id="statstable">
        <thead>
          <tr>
            <th>Sr</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <?php $i=1; ?>
          @foreach($internalstaff as $staff)
          <tr id="staff{{$staff->id}}">
            <th><?php echo $i++; ?></th>
            <th>{{$staff->firstname}}</th>
            <th>{{$staff->lastname}}</th>
            <th>{{$staff->email}}</th>
            <th>{{$staff->phonenumber}}</th>
            <th>
              <a href="{{route('corporate-admin.edit',['id'=>$staff->id])}}" class="editdeletebtn"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
              <a href="javascript:void(0)" class="editdeletebtn staffdelete" id="deletestaff"  data-id="{{$staff->id}}" data-toggle="confirmation" data-title="are you sure?"><i class="fa fa-trash" aria-hidden="true"></i></a>
              <a href="{{route('corporate-admin.status',['id'=>$staff->id])}}" class="disable_enablebtn">
              @if($staff->status=="enable")  
                  Disable
              @else
                  Enable    
              @endif    

            </a></th>
          </tr>

          @endforeach  
        </tbody>
      </table>
    </div>    
    
@endsection
  @section('scripts')
    <script type="text/javascript">
     
     $('.staffdelete[data-toggle=confirmation]').confirmation({
                  rootSelector: '[data-toggle=confirmation]',
                  container: 'body',
                  onConfirm: function() {
                     var id = $(this).data('id');
                     
                        $.ajax({
                                 type: "GET",
                                 url: "{{route('corporate-admin.delete')}}",
                                 data: {id:id},
                                 success: function () {                    
                                     $("#staff"+id).remove();
                                     toastr.success("Member Deleted Successfully");     
                                     
                                     }         
                             });
                  },
                }); 
    </script>
    <script type="text/javascript">
      $('#statstable').on('page.dt', function() {
        setTimeout(
          function() {
               $('.staffdelete[data-toggle=confirmation]').confirmation({
                            rootSelector: '[data-toggle=confirmation]',
                            container: 'body',
                            onConfirm: function() {
                               var id = $(this).data('id');
                               
                                  $.ajax({
                                           type: "GET",
                                           url: "{{route('corporate-admin.delete')}}",
                                           data: {id:id},
                                           success: function () {                    
                                               $("#staff"+id).remove();
                                               toastr.success("Member Deleted Successfully");     
                                               
                                               }         
                                       });
                            },
                          });
          }, 500);
      });
     
    </script>
    <script type="text/javascript">
      $('#statstable').on('order.dt', function() {
        setTimeout(
          function() {
               $('.staffdelete[data-toggle=confirmation]').confirmation({
                            rootSelector: '[data-toggle=confirmation]',
                            container: 'body',
                            onConfirm: function() {
                               var id = $(this).data('id');
                               
                                  $.ajax({
                                           type: "GET",
                                           url: "{{route('corporate-admin.delete')}}",
                                           data: {id:id},
                                           success: function () {                    
                                               $("#staff"+id).remove();
                                               toastr.success("Member Deleted Successfully");     
                                               
                                               }         
                                       });
                            },
                          });
          }, 500);
      });
     
    </script>
  @endsection