routes/web.php
		Route::get('/skills/gallery/slide/image','SkillController@skillGallerySlideImages')->name('skillslidergallery.images');
		Route::get('/skills/view/gallery/{id}','SkillController@viewGallery')->name('view.skillgallery');
		Route::get('/skills/video/show','SkillController@videoShow')->name('skill.video.show');

		Route::post('/skills/addtag','SkillController@addTag')->name('skill.addtag');
		Route::get('/skills/removetag','SkillController@removeTag')->name('skill.removetag');
		Route::post('/skills/add/video','SkillController@addSkillVideo')->name('add.skills.video');
		Route::post('/skillGalleryUpdate','SkillController@skillGalleryUpdate')->name('skillGalleryUpdate');
		Route::get('/skills/removemedia','SkillController@removeSkillMedia')->name('skills.removeMedia');	

		Route::get('/skills/search','SkillController@skillsSearch')->name('skills.search');
		Route::get('/skills/getTags','SkillController@getTags')->name('skills.getTags');
		
 
		Route::post('storeprofile','PortfolioController@storeprofile')->name('storeprofile');

		Route::post('changepassword','PortfolioController@changePassword')->name('changepassword');

 		Route::post('/rental/images','RentalController@storeRentalImages')->name('store.rental.images');
		Route::post('/rental/media','RentalController@storeRantalMedia')->name('store.rental.media');
		Route::post('/rental/addtag','RentalController@rentalAddTag')->name('rental.addtag');

		Route::get('/rental/removetag','RentalController@removeRentalTag')->name('rental.removetag');

		Route::get('/rental/removemedia','RentalController@removeRentalMedia')->name('rental.removeMedia');

		Route::post('/rental/add/images','RentalController@addRentalImages')->name('add.rental.images');

		Route::get('/rental/search','RentalController@rentalSearch')->name('rental.search');
		Route::get('/rental/gallery/slide/image','RentalController@rentalGallerySlideImages')->name('rentalslidergallery.images');
		Route::post('/rentalGalleryUpdate','RentalController@rentalGalleryUpdate')->name('rentalGalleryUpdate');
		Route::get('/rental/getTags','RentalController@getTags')->name('rental.getTags');
	
		Route::get('/rental/view/gallery/{id}','RentalController@viewGallery')->name('view.rentalgallery');

		Route::post('/rentalGalleryremove','RentalController@rentalGalleryRemove')->name('rentalGalleryRemove');

 		Route::get('/projectdata','ResumeController@projectdata')->name('projectdata');
		Route::get('/addworktitle','ResumeController@addworktitle')->name('addworktitle');
		Route::get('/addimdc','ResumeController@addimdc')->name('addimdc');
		Route::get('/roleDelete','ResumeController@roleDelete')->name('roleDelete');
		Route::get('/addrole','ResumeController@addrole')->name('addrole');
		Route::get('/updateRole','ResumeController@updateRole')->name('updateRole');
		Route::get('/addprojecttitle','ResumeController@addprojecttitle')->name('addprojecttitle');
		Route::get('/deleteProject','ResumeController@deleteProject')->name('deleteProject');
		Route::get('/editResume','ResumeController@editResume')->name('editResume');
		Route::get('/resumeSearch','ResumeController@resumeSearch')->name('resumeSearch');
		
		

 
		Route::get('/addrestriction','RestrictionController@addrestriction')->name('addrestriction');
		Route::get('/addnudity','RestrictionController@addnudity')->name('addnudity');

 		

 });



/** end route performers **/


/****************   InternalStaff Authentication ************************/

//Route::group(['domain' => 'talent.freemancasting.com','namespace'=>'InternalStaff','as'=>'internal-staff.'],function(){
Route::group(['prefix' => 'internal-staff','namespace'=>'InternalStaff','as'=>'internal-staff.'],function(){	
	Route::get('/','InternalStaffController@index')->name('internal-staff');
	Route::group(['namespace'=>'Auth'],function(){
		// Route::get('internal-staff/register', 'RegisterController@showRegistrationForm')->name('register');
		// Route::post('internal-staff/register', 'RegisterController@register')->name('signup');
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});
	
	
	/** AUTH IN INTERNAL STAFF **/
	Route::group(['middleware' => ['auth:internal-staff']],function(){
		Route::get('/','InternalStaffController@performersList')->name('performers.list');
		Route::get('performers/list','InternalStaffController@performersList')->name('performers.list');
		Route::get('add','InternalStaffController@add')->name('add');
		Route::get('performers/detail','InternalStaffController@performersDetail')->name('performers.detail');
		
		/** SCROLL **/
		Route::get('/performersScroll','InternalStaffController@performersScroll')->name('performersScroll');
		Route::get('/performersScrollSearch','SearchController@searchScroll')->name('performersScrollSearch');
		Route::get('/myperformers','InternalStaffController@myperformers')->name('myperformers');

		//list view
		Route::post('/saveflag','InternalStaffController@saveFlag')->name('saveFlag');
		Route::get('/listview','InternalStaffController@listView')->name('listview');

		Route::post('/removeflag','InternalStaffController@removeFlag')->name('removeflag');

		Route::post('/save/result','SearchController@searchResultSave')->name('search.result');		
		Route::get('/search/result/{id}','SearchController@SearchResultDisplay')->name('search.result.display');		

		Route::get('/search','SearchController@search')->name('search');
		Route::get('/search/selectoption','SearchController@searchSelectOption')->name('searchSelectOption');
		Route::get('/portfolio/getSliderImage','InternalStaffController@getSliderImage')->name('portfolio.getSliderImage');
		Route::get('/search/advanceselect','SearchController@advanceSearch')->name('advanceSearch');
		//internal profile Update 
		Route::post('/update/profile','InternalStaffController@updateProfile')->name('updateProfile');
		Route::post('changepassword','InternalStaffController@changePassword')->name('changepassword');
		Route::post('addperformer','InternalStaffController@addperformer')->name('addperformer');
		Route::get('/projectdata','ResumeController@projectdata')->name('projectdata');
Route::get('/savenotes','InternalStaffController@savenotes')->name('savenotes');
		Route::get('/deletenote','InternalStaffController@deletenote')->name('deletenote');
		Route::get('/editnote','InternalStaffController@editnote')->name('editnote');
		Route::get('/updatenote','InternalStaffController@updatenote')->name('updatenote');

	});


	/** END AUTH IN INTERNAL STAFF **/

});

/****************  InternalStaff Authentication ************************/


/****************   Corporate Admin Authentication ************************/

Route::group(['prefix' => 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
//Route::group(['domain' => 'talent.freemancasting.com','prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
	
	Route::get('/','CorporateAdminController@index')->name('corporate-admin');

	Route::group(['namespace'=>'Auth'],function(){


		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});



});
//Route::group(['prefix'=> 'corporate-admin','domain' => 'talent.freemancasting.com','namespace'=>'CorporateAdmin' ,'as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){

Route::group(['prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){
	Route::get('/form','CorporateAdminController@form')->name('form');
	Route::post('/addstaff','CorporateAdminController@store')->name('addstaff');
	Route::get('list','CorporateAdminController@list')->name('list'); 
	Route::get('edit/{id}','CorporateAdminController@edit')->name('edit');
	Route::post('store','CorporateAdminController@save')->name('store');
	Route::get('delete','CorporateAdminController@delete')->name('delete');	
	Route::get('status/{id}','CorporateAdminController@status')->name('status');
	Route::get('skintone','CorporateAdminController@tone')->name('skintone');	
	Route::get('eyes','CorporateAdminController@eyes')->name('eyes');	
	Route::get('availability','CorporateAdminController@Availability')->name('availability');	
	Route::get('performerstatus','CorporateAdminController@performerStatus')->name('performerstatus');	
		
	Route::get('documents','CorporateAdminController@documents')->name('documents');	
	Route::get('piercing','CorporateAdminController@piercing')->name('piercing');	
	Route::get('tattoo','CorporateAdminController@tattoo')->name('tattoo');	
	Route::get('helpdesk','CorporateAdminController@helpdesk')->name('helpdesk');	
	
	Route::get('haircolor','CorporateAdminController@haircolor')->name('haircolor');
	
	//hair facial list

	Route::get('hairfacial','CorporateAdminController@hairfacial')->name('hairfacial');	
	
	//hair Style list

app/Models/v1/InternalStaff.php
<?php

namespace App\Models\v1;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\InternalStaffResetPasswordnotification;

class InternalStaff extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   protected $table  = 'internal_staffs';
    protected $guard = 'internal-staff';
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new InternalStaffResetPasswordnotification($token));
    }
    protected $fillable = [
        'lastname',
        'firstname',
        'email',
        'phonenumber',
        'password',
         'status',
        'remember_token',
        'created_at',
        'updated_at'  
    ];
    protected $appends  =[
        'full_name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
      function getFullNameAttribute() {
          return $this->firstname . ' ' . $this->lastname;
    }
}

resources/views/internal-staff/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<?php $internal_staff =Auth::user();?>
<head>
    <title>@yield('title','freemancasting')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content=""/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/toastr.min.css') }}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('assets/css/dropzone.css') }}" rel="stylesheet" type="text/css" />
    
    <link href="{{ asset('assets/fontawesome-pro/css/all.css') }}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{{ asset('assets/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/nice-select.css') }}">

    <link rel="stylesheet" href="{{ asset('assets/css/VueAgile.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/jquery.imageview.css') }}">
    <link rel="stylesheet"  href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">    

    

</head>

<body>
    @if(Auth::guard('internal-staff')->check())
    @include('internal-staff.layouts.header') 
    @yield('content')
    @else
    @yield('content')
    @endif
   
    @include('internal-staff.layouts.footer') 
      
</body>



<script type="text/javascript" src="{{ asset('assets/js/jquery.js')}}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>
<script src="{{ asset('assets/js/dropzone.js')}}"></script>
<script src="{{ asset('assets/js/toastr.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/fontawesome-pro/js/all.js')}}"></script>
<script src="{{ asset('assets/js/select2.min.js')}}"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="{{ asset('assets/js/dataTable.js')}}"></script>
<script src="{{ asset('assets/js/dataTableBoot.js')}}"></script>
<script src="{{ asset('assets/js/masonry.pkgd.min.js')}}"></script>
<script src="{{ asset('assets/js/vue.min.js')}}"></script>
<script src="{{ asset('assets/js/VueAgile.umd.min.js')}}"></script>
<script src="{{ asset('assets/js/jquery.mask.min.js')}}"></script>
<script src="{{ asset('assets/js/jquery.nice-select.js')}}"></script>
<script src="{{ asset('assets/js/jquery.imageview.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.devbridge-autocomplete/1.4.9/jquery.autocomplete.min.js" integrity="sha256-CA1BfwIJ3XnP7Jx7XaRKrrmJILIn+4skJeDB2YVo6nw=" crossorigin="anonymous"></script>

<script type="text/javascript">

 
  
// $('.gelimgleftbox').imageview(); 
   



 //  $(document).ready(function () {
 // //   Disable full page
 //    $("body").on("contextmenu",function(e){
 //      return false;
 //    });
    
 //    //Disable part of page
 //    $('body').bind('cut copy paste', function (e) {
 //      e.preventDefault();
 //    });
    

 //  });
 //  $(document).keydown(function (event) {
   
 //    if (event.keyCode == 123 || event.keyCode == 44 || event.ctrlKey && 
 //            (event.keyCode === 67 || 
 //             event.keyCode === 86 || 
 //             event.keyCode === 85 || 
 //             event.keyCode === 117)) { // Prevent F12
 //      return false;
 //    } else if (event.ctrlKey && event.shiftKey && event.keyCode == 73) { // Prevent Ctrl+Shift+I        
 //      return false;
 //    }
 //  });
      
// function copyToClipboard() {
//   // Create a "hidden" input
//   var aux = document.createElement("input");
//   // Assign it the value of the specified element
//   aux.setAttribute("value", "Você não pode mais dar printscreen. Isto faz parte da nova medida de segurança do sistema.");
//   // Append it to the body
//   document.body.appendChild(aux);
//   // Highlight its content
//   aux.select();
//   // Copy the highlighted text
//   document.execCommand("copy");
//   // Remove it from the body
//   document.body.removeChild(aux);
//   //alert("Print screen desabilitado.");
// }

$(window).keyup(function(e){
  if(e.keyCode == 44){
 //   copyToClipboard();
  }
}); 
      $(document).ready(function(){
       
        jQuery('#unionmodel').select2({
         placeholder:'Select Union'
        });
        jQuery('#gendermodel').select2({
         placeholder:'Select Gender'
        });
        jQuery('#agentselect').select2({
         placeholder:'Select Agent'
        });
        $('#DOB').datepicker({
          dateFormat: 'MM dd yy'
          
        });
        
        $("#passwordDisplay").hide();

         $("#ChangePassword").click(function(){

          $("#passwordDisplay").show();
          $("#ProfileDisplay").hide();
        });

         $("#profileformShow").click(function(){
          $("#passwordDisplay").hide();
          $("#ProfileDisplay").show();
        });
 
 


      });
         
         $("#PasswordChangeBtn").click(function(){
           ChangePasswordData =$("#ChangePasswordForm").serialize();
           $.ajaxSetup({
            headers: {
              'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
          });
           $.ajax({
               url:"{{route('internal-staff.changepassword')}}",
               type:"post",
               data:ChangePasswordData,
               success:function(response)
               {
                 if(response.status == true)
                 {
                   toastr.success(response.message);
                  location.reload();
                 }

                 if(response.status == false)
                 {
                   toastr.error(response.message);
                 }
               },
               error:function(response)
               {

               }
           });
       }); 
        $(document).ready(function(){

           src = "{{route('performers.agentlist')}}";

       $( "#agent" ).autocomplete({
       source: function(request, response) {
               $.ajaxSetup({
                    headers: {
                      'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                  });
               $.ajax({
                   
                   type: 'POST',
                   url: src,
                   data: {
                       term : $("#agent").val()
                   },
                   success: function(data) {
                        if (!data.length) {
                       var result = [{ label: "no results", value: response.term }];
                       response(result);
                   }
                       response(data);

                   },
                   
               });
           },
           minLength: 1,
           appendTo: "#categorysomeElem",
       select: function(event, ui) {
           var label = ui.item.label;
                       if (label === "Add Agent") {
                           event.preventDefault();
                           // alert($("#agent").val());
                           $.ajaxSetup({
                                headers: {
                                  'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                                }
                              });
                           $.ajax({
                               
                               type: 'POST',
                               url: "{{route('performers.addinagentlist')}}",
                               data: {
                                    data : $("#agent").val()
                               },
                               success: function(data) {

                                 $('#agent_id').val(data);
                                 toastr.success("Agent Added Successfully");

                               },
                               
                           })

                   }
          else{         
         $('#agent_id').val(ui.item.id);
           }
       },
    change: function (event, ui) {
        if (ui.item == null){ 
         //here is null if entered value is not match in suggestion list
           toastr.warning("Please Select Agent");
            $(this).val((ui.item ? ui.item.id : ""));
        }
    },
       response: function(event, ui) {
           if (!ui.content.length) {

               var noResult = { value:"",label:"No results found" };
              // var newitem = { value:"test",label:"Add Agent"}
                ui.content.push(noResult);
               //ui.content.push(newitem);

           }
         }  
        });

           });   

           $("#staffupdateProfile").click(function(){
           
          EditformData = $("#staffProfileEdit").serialize();

          $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
          $.ajax({
              url:"{{route('internal-staff.updateProfile')}}",
              type:'POST',
              data:EditformData,
              success:function(response)
              {
               
                  if(response.status == true)
                  {
                      toastr.success(response.message);
                      location.reload(1500);
                  }
                  else{
                    toastr.error(response.message);
                  }
              }
          });

      });  
</script>
@yield('scripts')

</html>

resources/views/internal-staff/layouts/footer.blade.php
<?php $internal_staff =Auth::user();?>
<div class="modal fade userinfoboedit" id="myModal15" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">      
      <div class="modal-body">        
        <div class="editboxprofilin">
          <div class="totitleaddris">
            <h4>Edit User Profile</h4>
            <button type="button" class="close" data-dismiss="modal"><i class="fal fa-times"></i></button>
          </div>

          <input type="hidden" name="performers_user" id="performers_user" value="{{isset($per_id) ? $per_id : '' }}">

          @if(isset($internal_staff))
          <!-- ProfileData --> 
          <div class="detailprofcover" id="ProfileDisplay">
            <form method="post" id="staffProfileEdit">
            <div class="form-group">
              <label for="usr">First Name</label>
              <input type="text" value="{{$internal_staff->firstname}}" name="firstname" class="form-control" >
            </div>
            <div class="form-group">
              <label for="usr">Last Name</label>
              <input type="text" value="{{$internal_staff->lastname}}" name="lastname" class="form-control" >
            </div>
            <div class="form-group">
              <label for="usr">Email</label>
              <input type="text" name="email" value="{{$internal_staff->email}}" class="form-control" >
            </div>
            <div class="form-group">
              <label for="usr">Phone</label>
              <input type="text" name="phonenumber" value="{{$internal_staff->phonenumber}}" class="form-control"   data-mask="(000) 000-0000">
            </div>
            <div class="savebtnbox">
              <button type="button" id="staffupdateProfile" class="btn">Save</button>

              <button type="button" id="ChangePassword" class="btn">Change Password</button>
            </div>
            <input type="hidden" value="{{$internal_staff->id}}" name="id" class="form-control" >
          </form>
          </div>
          
          <!-- ProfilePassword -->
          <div class="detailprofcover" id="passwordDisplay">
            <form method="post" id="ChangePasswordForm">
            <div class="form-group">
              <label for="usr">Old Password</label>
              <input type="password" value="" name="old_password" class="form-control" >
            </div>
            <div class="form-group">
              <label for="usr">New Password</label>
              <input type="password" value="" name="password" class="form-control" id="usr">
            </div>
            <div class="form-group">
              <label for="usr">Confirm Password</label>
              <input type="password" value="" name="confirm_password" class="form-control" >
            </div>
            <div class="savebtnbox">
              <button type="button" id="PasswordChangeBtn" class="btn">Change Password</button>
              <button type="button" id="profileformShow" class="btn">Profile </button>
            </div>
          </form>
          </div>
          @endif
          
        </div>
      </div>
    </div>    
  </div>
</div>

@if(!isset($is_show))
<script type="text/javascript">
 jQuery(document).ready(function(){
 
  jQuery('.internalStaffAction,.deleteresumeconfirm,.deletefield a,.morebtneddil,.AddTag,.btnremadd a,.gelimgleftbox li .deleteimgbox,#editAppearance,.addbtnbotbox,.btnAddPortfolioGallery,.deleteimageconfirm,.doctslistdit_title_hide,.audioDeleteconfirm,.skill_resume_Search_hide,.hidesearch,.btnAddRentalGallery,.btnAddClosetGallery,.hiddenforInternalStaff').addClass('hidden');
    

jQuery('#showForIntenalStaff').removeClass("hidden");

    $(".fieldForm").hide();
       $("#staffupdateProfile").click(function(){
      EditformData = $("#staffProfileEdit").serialize();

      $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
      $.ajax({
          url:"{{route('internal-staff.updateProfile')}}",
          type:'POST',
          data:EditformData,
          success:function(response)
          {
           
              if(response.status == true)
              {
                  toastr.success(response.message);
                  location.reload(1500);
              }
              else{
                toastr.error(response.message);
              }
          }
      });

  });
 });
</script>

<script type="text/javascript">
  
  $(document).ready(function(){    

   $.ajax({
        url:"{{route('internal-staff.portfolio.getSliderImage')}}",
        type:'get',
       
        data:{id:$.trim(jQuery('#performers_user').val())},
        success:function(response){
           showsliderimg(response.msg);
            
        }

  });
    });
function showsliderimg(img){
  
 setTimeout(function(){ 
  Vue.use(VueAgile);
    app = new Vue({
    el: '#mySidebarImage',
    components: {
    agile: VueAgile },
  data() {
    return {
      asNavFor1: [],
      asNavFor2: [],
      options1: {
        dots: false,
        fade: true,
        navButtons: false },
      options2: {
        autoplay: false,
        centerMode: false,
        dots: false,
        navButtons: false,
        infinite : false,
        slidesToShow: 3,
        responsive: [
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 4 } },

        {
          breakpoint: 1000,
          settings: {
            navButtons: true } }] },


          slides: img
          };


  },
  mounted() {
    this.asNavFor1.push(this.$refs.thumbnails);
    this.asNavFor2.push(this.$refs.main);
  } }); }, 1000);

 }
 
 $(document).ready(function() {
    $(".set > a").on("click", function() {
      if ($(this).hasClass("active")) {
        $(this).removeClass("active");
        $(this)
        .siblings(".content")
        .slideUp(200);
        $(".set > a i")
        .removeClass("fa-minus")
        .addClass("fa-plus");
      } else {
        $(".set > a i")
        .removeClass("fa-minus")
        .addClass("fa-plus");
        $(this)
        .find("i")
        .removeClass("fa-plus")
        .addClass("fa-minus");
        $(".set > a").removeClass("active");
        $(this).addClass("active");
        $(".content").slideUp(200);
        $(this)
        .siblings(".content")
        .slideDown(200);
      }
    });
  });
</script>
@endif

resources/views/internal-staff/layouts/header.blade.php
<header class="clainternal_staffhed">
  <div class="hedpartlr">
    <div class="lefttitlebox">
      <div class="imageLogo">
        <a href="{{ route('internal-staff.performers.list') }}">
        <img src="{{ asset('assets/images/logo.png') }}" alt="">
      </a>
      </div>
    </div> 
    <div class="rightnotusei">
      <div class="inerboxsetpart">
        	<a href="javascript:void(0)" class="belllogbtn"><i class="far fa-bell"></i></a>
        	<a href="javascript:void(0)" class="active" type="button" data-toggle="modal" data-target="#myModal15"><i class="fas fa-user"></i></a>
          <!-- <a href="javascript:void(0)" class="active" type="button" data-toggle="modal" data-target="#myModal15">
            <div class="userprofileiconset_inerimg">
              <div class="hexagon_userprofileset_maincl1">
                <div class="hexagon_userprofileset_inercl1">
                  <img src="http://192.168.1.18/freemancasting/public/storage/performers/1/1563363531Chrysanthemum.jpg">
                </div>    
              </div>    
            </div>
          </a>  -->
        	<a href="{{ route('internal-staff.logout') }}" onclick="event.preventDefault();
          	document.getElementById('logout-form').submit();" class="belllogbtn">
         		<i class="fas fa-power-off"></i>
      	</a>
      	<form id="logout-form" action="{{ route('internal-staff.logout') }}" method="POST" style="display: none;">
          	@csrf
      	</form>
      </div> 
    </div> 
  </div>
 
</header>
  <div class="tabdataperfbox internalStaffAction">
    <div class="leftfreeperbtn">
      <a href="{{ route('internal-staff.performers.list') }}" class="activebt">Freeman Casting Database</a>
      <!-- <a href="{{ route('internal-staff.myperformers') }}" >My Performers</a> -->
    </div>
    <div class="rightretperfbtn">
      <!-- <a href="javascript:void(0)"><i class="fal fa-plus"></i>Create Performer</a> -->
      <a href="javascript:void(0)" class="active" type="button" data-toggle="modal" data-target="#PerformerModel"><i class="fal fa-plus"></i> Create Performer</a>
    </div>
  </div>