routes/web.php
		// Route::get('internal-staff/register', 'RegisterController@showRegistrationForm')->name('register');
		// Route::post('internal-staff/register', 'RegisterController@register')->name('signup');
		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});
	
	
	/** AUTH IN INTERNAL STAFF **/
	Route::group(['middleware' => ['auth:internal-staff']],function(){
		Route::get('/','InternalStaffController@performersList')->name('performers.list');
		Route::get('performers/list','InternalStaffController@performersList')->name('performers.list');
		Route::get('add','InternalStaffController@add')->name('add');
		Route::get('performers/detail','InternalStaffController@performersDetail')->name('performers.detail');
		
		/** SCROLL **/
		Route::get('/performersScroll','InternalStaffController@performersScroll')->name('performersScroll');
		Route::get('/performersScrollSearch','SearchController@searchScroll')->name('performersScrollSearch');
		Route::get('/myperformers','InternalStaffController@myperformers')->name('myperformers');

		//list view
		Route::post('/saveflag','InternalStaffController@saveFlag')->name('saveFlag');
		Route::get('/listview','InternalStaffController@listView')->name('listview');

		Route::post('/removeflag','InternalStaffController@removeFlag')->name('removeflag');

		Route::post('/save/result','SearchController@searchResultSave')->name('search.result');		
		Route::get('/search/result/{id}','SearchController@SearchResultDisplay')->name('search.result.display');		

		Route::get('/search','SearchController@search')->name('search');
		Route::get('/search/selectoption','SearchController@searchSelectOption')->name('searchSelectOption');
		Route::get('/portfolio/getSliderImage','InternalStaffController@getSliderImage')->name('portfolio.getSliderImage');
		Route::get('/search/advanceselect','SearchController@advanceSearch')->name('advanceSearch');
		//internal profile Update 
		Route::post('/update/profile','InternalStaffController@updateProfile')->name('updateProfile');
		Route::post('changepassword','InternalStaffController@changePassword')->name('changepassword');
		Route::post('addperformer','InternalStaffController@addperformer')->name('addperformer');
		Route::get('/projectdata','ResumeController@projectdata')->name('projectdata');
Route::get('/savenotes','InternalStaffController@savenotes')->name('savenotes');
		Route::get('/deletenote','InternalStaffController@deletenote')->name('deletenote');
		Route::get('/editnote','InternalStaffController@editnote')->name('editnote');
		Route::get('/updatenote','InternalStaffController@updatenote')->name('updatenote');

	});


	/** END AUTH IN INTERNAL STAFF **/

});

/****************  InternalStaff Authentication ************************/


/****************   Corporate Admin Authentication ************************/

Route::group(['prefix' => 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
//Route::group(['domain' => 'talent.freemancasting.com','prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.'],function(){
	
	Route::get('/','CorporateAdminController@index')->name('corporate-admin');

	Route::group(['namespace'=>'Auth'],function(){


		Route::get('login', 'LoginController@showLoginForm')->name('login');
		Route::post('login', 'LoginController@login')->name('login');
		Route::post('logout', 'LoginController@logout')->name('logout');
		Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
		Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
		Route::post('password/update', 'ResetPasswordController@reset')->name('password.update');
		Route::get('password/reset/{token}', 
			'ResetPasswordController@showResetForm')->name('password.reset');
	});



});
//Route::group(['prefix'=> 'corporate-admin','domain' => 'talent.freemancasting.com','namespace'=>'CorporateAdmin' ,'as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){

Route::group(['prefix'=> 'corporate-admin','namespace'=>'CorporateAdmin','as'=>'corporate-admin.', 'middleware' => ['auth:corporate-admin']], function(){
	Route::get('/form','CorporateAdminController@form')->name('form');
	Route::post('/addstaff','CorporateAdminController@store')->name('addstaff');
	Route::get('list','CorporateAdminController@list')->name('list'); 
	Route::get('edit/{id}','CorporateAdminController@edit')->name('edit');
	Route::post('store','CorporateAdminController@save')->name('store');
	Route::get('delete','CorporateAdminController@delete')->name('delete');	
	Route::get('status/{id}','CorporateAdminController@status')->name('status');
	Route::get('skintone','CorporateAdminController@tone')->name('skintone');	
	Route::get('eyes','CorporateAdminController@eyes')->name('eyes');	
	Route::get('availability','CorporateAdminController@Availability')->name('availability');	
	Route::get('performerstatus','CorporateAdminController@performerStatus')->name('performerstatus');	
		
	Route::get('documents','CorporateAdminController@documents')->name('documents');	
	Route::get('piercing','CorporateAdminController@piercing')->name('piercing');	
	Route::get('tattoo','CorporateAdminController@tattoo')->name('tattoo');	
	Route::get('helpdesk','CorporateAdminController@helpdesk')->name('helpdesk');	
	
	Route::get('haircolor','CorporateAdminController@haircolor')->name('haircolor');
	
	//hair facial list

	Route::get('hairfacial','CorporateAdminController@hairfacial')->name('hairfacial');	
	
	//hair Style list

	Route::get('hairstyle','CorporateAdminController@hairstyle')->name('hairstyle');	
	
	//Body Trait list

	Route::get('bodytrait','CorporateAdminController@bodytrait')->name('bodytrait');	
	
	Route::get('ethnicity','CorporateAdminController@ethnicity')->name('ethnicity');	
	Route::get('nationality','CorporateAdminController@nationality')->name('nationality');	
	Route::get('handedness','CorporateAdminController@handedness')->name('handedness');	
		
	Route::get('agent','CorporateAdminController@Agent')->name('agent');	
	Route::get('agency','CorporateAdminController@Agency')->name('agency');	
	Route::get('union','CorporateAdminController@Union')->name('Union');	
	Route::get('flag','CorporateAdminController@Flag')->name('Flag');	
	Route::get('hairlength','CorporateAdminController@hairlength')->name('hairlength');	
	Route::get('vehicle_type','CorporateAdminController@vehicletype')->name('vehicletype');
	Route::get('vehicle_year','CorporateAdminController@vehicleyear')->name('vehicleyear');
	Route::get('vehicle_make','CorporateAdminController@vehiclemake')->name('vehiclemake');
	Route::get('vehicle_model','CorporateAdminController@vehiclemodel')->name('vehiclemodel');
	Route::get('vehicle_condition','CorporateAdminController@vehiclecondition')->name('vehiclecondition');
	Route::get('vehicle_accessories','CorporateAdminController@vehicleaccessories')->name('vehicleaccessories');
	Route::post('addtone','CorporateAdminController@addtone')->name('addtone');
	Route::post('addeyes','CorporateAdminController@addeyes')->name('addeyes');
	Route::post('addpiercing','CorporateAdminController@addPiercing')->name('addpiercing');
	Route::post('addtattoo','CorporateAdminController@addTattoo')->name('addtattoo');
	Route::post('addunion','CorporateAdminController@addunion')->name('addunion');
	Route::post('addagent','CorporateAdminController@addagent')->name('addagent');
	Route::post('addagency','CorporateAdminController@addAgency')->name('addagency');
	Route::post('addflag','CorporateAdminController@addflag')->name('addflag');
	Route::post('addhelpdesk','CorporateAdminController@addhelpdesk')->name('addhelpdesk');
	Route::post('addvehicle_type','CorporateAdminController@addvehicletype')->name('addvehicletype');
	Route::post('addvehicle_make','CorporateAdminController@addvehiclemake')->name('addvehiclemake');
	Route::post('addvehicle_accessories','CorporateAdminController@addvehicleaccessories')->name('addvehicleaccessories');

	Route::post('adddocument','CorporateAdminController@adddocument')->name('adddocument');
	Route::post('addavailability','CorporateAdminController@addavailability')->name('addavailability');
	Route::post('addstatus','CorporateAdminController@addstatus')->name('addstatus');
	Route::post('addtag','CorporateAdminController@addtag')->name('addtag');
	Route::post('addhaircolor','CorporateAdminController@addhaircolor')->name('addhaircolor');
	Route::post('addnationality','CorporateAdminController@addnationality')->name('addnationality');
	Route::post('addethnicity','CorporateAdminController@addethnicity')->name('addethnicity');
	Route::post('addhandedness','CorporateAdminController@addhandedness')->name('addhandedness');
	Route::post('addhairlength','CorporateAdminController@addhairlength')->name('addhairlength');
	Route::post('addhairfacial','CorporateAdminController@addhairfacial')->name('addhairfacial');
	Route::post('addhairstyle','CorporateAdminController@addhairstyle')->name('addhairstyle');
	Route::post('addbodytrait','CorporateAdminController@addbodytrait')->name('addbodytrait');
	Route::post('updatetone','CorporateAdminController@updatetone')->name('updatetone');
	Route::post('updateethnicity','CorporateAdminController@updateethnicity')->name('updateethnicity');
	Route::post('updateeyes','CorporateAdminController@updateeyes')->name('updateeyes');

app/Models/v1/CorporateAdmin.php
<?php

namespace App\Models\v1;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\CorporateAdminResetPasswordNotification;

class CorporateAdmin extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   protected $table  = 'corporate_admins';
   protected $guard = 'corporate-admin';

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new CorporateAdminResetPasswordNotification($token));
    }
    
    protected $fillable = [
        'name',
        'email',
        'phonenumber',
        'password',
        'remember_token',
        'created_at',
        'updated_at'  
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

 

app/Http/Controllers/CorporateAdmin/document.php
@extends('performers.layouts.app')
@section('content')
<div class="wctleftrightbox">
  @if($performer->applicationfor == "Group")
  @include('performers.layouts.groupSidebar')  
  @else
  @include('performers.layouts.sidebar')  
  @endif
     <div class="rightallditinwct">
   <!--  <div class="searchbarboxfilt">
      <div class="srchbox">        
        <div class="form-group">
          <i class="far fa-search"></i>
          <input type="text" class="form-control" id="skillSearch" placeholder="Search">
        </div>
      </div>
      <div class="addandtagbox">
        <div class="addatribut">
          <a href="javascript:void(0)" type="button" data-toggle="modal" data-target="#myDocumentsModal"><i class="far fa-plus"></i>New Document</a>
        </div>
        <div class="tagboxright">
          <a href="javascript:void(0)"><i class="far fa-tag"></i></a>
        </div>
      </div>
    </div> -->
    <div class="addflagshidbox">
      <div class="accordion-container">
        <div class="set hedtobox">
          <div class="srchbox hidden">        
            <div class="form-group">
              <i class="far fa-search"></i>
             <input type="text" class="form-control" id="" placeholder="Search">
            </div>
          </div>
      @if($authtype=='performer')     
     @else
     @include('performers.flag')
     @endif       
        </div>      
      </div>
    </div>
  <div class="topbarbotdivcover">
    @if($authtype=='performer')
    @include('performers.layouts.tabbar')
    @else
    @include('performers.layouts.internal-tabbar')
    @endif
  
    <div class="doctslistdit">
      <div class="doctslistdit_title">

        <h3>Documents List</h3>
      </div>
      <div class="errbrtext">
        <i class="far fa-info-circle"></i>
        <p>Please be sure to store these documents in an easy to find locations so that you can bring them to set. You will not be able to work without these documents. Do not upload them to this system in any capacity.</p>
      </div>
      <div class="dpnpiwsbox">
        <div class="dpnpiwsbox_partdiv">
       @foreach($document as $doc)
        
          <div class="dpnpiwsbox_inerfullw">
            <div class="lefttextdpmpiws">
              <p>{{ $doc->doument_name }}</p>
            </div>
     <!--        <div class="righttextdpmpiws">  
              <div class="custheckedbox Checkedgrn">
                <input class="styled-checkbox documentcheckbox" id="{{$doc->id}}" type="checkbox" value="{{$doc->id}}" checked>
                <label for="{{$doc->id}}">Checked</label>
              </div>
              <div class="custheckedbox Checkedred">
                <input class="styled-checkbox documentcheckbox" id="{{$doc->id}}" type="checkbox" value="{{$doc->id}}">
                <label for="{{$doc->id}}">Not Checked</label>
              </div>
            </div> -->
          </div>  
          
           
          @endforeach
         
        </div>
        <div class="dpnpiwsbox_partdiv">
          @foreach($documentna as $nadoc)
          <div class="dpnpiwsbox_inerfullw">
            <div class="lefttextdpmpiws">
              <p>{{ $nadoc->doument_name }}</p>
            </div>
            <div class="righttextdpmpiws">
              <div class="notaplibox"><i class="far fa-minus-square"></i> <p> Not applicable</p></div>
            </div>
          </div>
          @endforeach          
        
        </div>



      </div>
      

  </div>
  
</div>

  
</div>
</div>
</div>



@endsection
@section('scripts')
<script type="text/javascript">
    $('.documentcheckbox').on('change', function(){ 
        id=$(this).attr('id');
        if (this.checked) {
             $.ajax({

                type: "POST",
                url: "{{route('performers.adddocument')}}",
                headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
                data: {
                        id:id
                      },
                success: function (data) {
                       // console.log(data);
                       toastr.success(data.message);
                      }         
            });
        }
        else{
           $.ajax({

              type: "POST",
              url: "{{route('performers.removedocument')}}",
              headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
              data: {
                      id:id
                    },
              success: function (data) {
                       toastr.success(data.message); 
                    }         
          });         
        }
    });
</script>
@include('performers.commonSkill')
@endsection

resources/views/corporate-admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>admin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content=""/>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  
  <link rel="stylesheet" href="{{ asset('assets/corporate-admin/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/corporate-admin/font-awesome/css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/corporate-admin/css/styles.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/corporate-admin/css/select2.min.css') }}">

  <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/css/toastr.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/css/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">

</head>
<body>
 	@include("corporate-admin.layouts.header") 

	<div class="parettow_coverbox">
		<div class="left_paretboxpart">
      @include("corporate-admin.layouts.sidebar")
    </div>
    <div class="right_paddingboxpart">
      @yield('content')
		</div>	
	</div>
	@include("corporate-admin.layouts.js")
	@yield('scripts')
	 
   <script>
      $(document).on("click",".myBtn",function() {
        $(this).parent('li').find(".myDropdown").toggleClass("show");
        if ($(this).find(".fa-minus").length > 0) {
            $(this).find("i").addClass("fa-plus").removeClass("fa-minus");
        } else {
            $(this).find("i").addClass("fa-minus").removeClass("fa-plus");
        }
      })

   </script>
</body>
</html>

resources/views/corporate-admin/layouts/content.blade.php
@extends('layouts.app')
@section('content')
		<form>
      <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
      <div class="form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>	
@endsection

resources/views/corporate-admin/layouts/header.blade.php
<header class="bgheader_bgcolor">
  <div class="logo_leftbox">
    <div class="imageLogo">
      <img src="{{ asset('assets/images/logo.png') }}" alt="">
    </div>
  </div>

  <div class="logout_rightbox">

      <a href="{{ route('corporate-admin.logout') }}" onclick="event.preventDefault();
        	document.getElementById('logout-form').submit();">
       		<img src="{{ asset('assets/svg/power-off.svg') }}" alt="">
    	</a>
    	<form id="logout-form" action="{{ route('corporate-admin.logout') }}" method="POST" style="display: none;">
        	@csrf
    	</form>
  </div>
</header>

resources/views/corporate-admin/layouts/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content=""/>
  <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/font-awesome/css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">    
</head>
<body>

 @yield('content')
 <script type="text/javascript" src="{{asset('assets/js/jquery.js') }}"></script>
 <script src="{{asset('assets/js/bootstrap.min.js') }}"></script>
  
</body>
</html>

resources/views/corporate-admin/layouts/sidebar.blade.php
    <div class="innercategories">
      <ul>
      <!--  <li>
          <a href="index.html">Dashboard</a>
        </li>  -->      
       <!--  <li class="{{Request::is('corporate-admin/form')?'activelist':''}}">
          <a href="{{route('corporate-admin.form')}}">Patients</a>
        </li> -->
        <li class="{{Request::is('corporate-admin/list')?'activelist':''}}">
          <a href="{{route('corporate-admin.list')}}">Internal Staff</a>
        </li>
      
       
        <li>
            <a href="javascript:void(0)" class="plusbttnbox myBtn">Appearance <i class=" {{ (Request::route()->getName() == 'corporate-admin.eyes') || (Request::route()->getName() == 'corporate-admin.ethnicity') || (Request::route()->getName() == 'corporate-admin.hairlength') || (Request::route()->getName() == 'corporate-admin.handedness')  || (Request::route()->getName() == 'corporate-admin.skintone')  || (Request::route()->getName() == 'corporate-admin.nationality')  || (Request::route()->getName() == 'corporate-admin.haircolor') ? 'fa fa-minus' : 'fa fa-plus' }}" aria-hidden="true" ></i></a>
            <div class="dropdown custmenbox">
              <!-- <button id="myBtn" class="dropbtn">Dropdown</button> -->



              <div  class="dropdown-content myDropdown {{ (Request::route()->getName() == 'corporate-admin.eyes') || (Request::route()->getName() == 'corporate-admin.ethnicity') || (Request::route()->getName() == 'corporate-admin.hairlength') || (Request::route()->getName() == 'corporate-admin.handedness')  || (Request::route()->getName() == 'corporate-admin.skintone')  || (Request::route()->getName() == 'corporate-admin.nationality')  ||
              (Request::route()->getName() == 'corporate-admin.hairfacial')  ||
              (Request::route()->getName() == 'corporate-admin.hairstyle')  ||
              (Request::route()->getName() == 'corporate-admin.bodytrait')  ||
               (Request::route()->getName() == 'corporate-admin.haircolor') ? 'show' : '' }}">      

                <a  class="{{Request::is('corporate-admin/eyes')?'activelist':''}}" href="{{route('corporate-admin.eyes')}}">Eyes</a>
                <a class="{{Request::is('corporate-admin/ethnicity')?'activelist':''}}" href="{{route('corporate-admin.ethnicity')}}">Ethnicity</a>

                <a  class="{{Request::is('corporate-admin/hairlength')?'activelist':''}}" href="{{route('corporate-admin.hairlength')}}">Hair Length</a> 
                
                <a  class="{{Request::is('corporate-admin/hairfacial')?'activelist':''}}" href="{{route('corporate-admin.hairfacial')}}">Hair Facial</a>
                
                <a  class="{{Request::is('corporate-admin/hairstyle')?'activelist':''}}" href="{{route('corporate-admin.hairstyle')}}">Hair Style</a>
                
                <a  class="{{Request::is('corporate-admin/bodytrait')?'activelist':''}}" href="{{route('corporate-admin.bodytrait')}}">Body Trait</a>        
                
                <a href="{{route('corporate-admin.handedness')}}"  class="{{Request::is('corporate-admin/handedness')?'activelist':''}}">Handedness</a>
                
                <a href="{{route('corporate-admin.skintone')}}" class="{{Request::is('corporate-admin/skintone')?'activelist':''}}">Skin Tone</a>
                
                <a href="{{route('corporate-admin.nationality')}}" class="{{Request::is('corporate-admin/nationality')?'activelist':''}}">Nationality</a>
                
                <a href="{{route('corporate-admin.haircolor')}}" class="{{Request::is('corporate-admin/haircolor')?'activelist':''}}">Hair Color</a>

              </div>
            </div>
        </li>
         <li class="{{Request::is('corporate-admin/tags')?'activelist':''}}">

          <a href="{{route('corporate-admin.tags')}}">Tags</a>
        </li>
         
        <li class="{{Request::is('corporate-admin/documents')?'activelist':''}}">
          <a href="{{route('corporate-admin.documents')}}">Documents</a>
        </li>
        <li class="{{Request::is('corporate-admin/agent')?'activelist':''}}">
          <a href="{{route('corporate-admin.agent')}}">Agent</a>
        </li>
        <li class="{{Request::is('corporate-admin/union')?'activelist':''}}">
          <a href="{{route('corporate-admin.Union')}}">Union</a>
        </li>
        <li class="{{Request::is('corporate-admin/flag')?'activelist':''}}">
          <a href="{{route('corporate-admin.Flag')}}">Flag</a>
        </li>
        <li class="{{Request::is('corporate-admin/agency')?'activelist':''}}">
          <a href="{{route('corporate-admin.agency')}}">Agency</a>
        </li>
        <li class="hidden {{Request::is('corporate-admin/piercing')?'activelist':''}}">
          <a href="{{route('corporate-admin.piercing')}}">Piercing</a>
        </li>
        <li class="hidden {{Request::is('corporate-admin/tattoo')?'activelist':''}}">
          <a href="{{route('corporate-admin.tattoo')}}">Tattoos</a>
        </li>
        <li class="hidden">
            <a href="javascript:void(0)" class="plusbttnbox myBtn">Vehicles <i class="fa fa-plus" aria-hidden="true"></i></a>
            <div class="dropdown custmenbox">
              <!-- <button id="myBtn" class="dropbtn">Dropdown</button> -->
              <div  class="dropdown-content myDropdown ">      

                <a  class="{{Request::is('corporate-admin/vehicle_type')?'activelist':''}}" href="{{route('corporate-admin.vehicletype')}}">Vehicle Type</a>
                <a  class="{{Request::is('corporate-admin/eyes')?'activelist':''}}" href="{{route('corporate-admin.eyes')}}">Vehicle Year</a>
                <a  class="{{Request::is('corporate-admin/vehicle_make')?'activelist':''}}" href="{{route('corporate-admin.vehiclemake')}}">Vehicle Make</a>
                <a  class="{{Request::is('corporate-admin/eyes')?'activelist':''}}" href="{{route('corporate-admin.eyes')}}">Vehicle Model</a>
                <a  class="{{Request::is('corporate-admin/eyes')?'activelist':''}}" href="{{route('corporate-admin.eyes')}}">Vehicle Condition</a>
                <a  class="{{Request::is('corporate-admin/vehicle_accessories')?'activelist':''}}" href="{{route('corporate-admin.vehicleaccessories')}}">Accessories</a>
              </div>
            </div>
        </li>
        <li class="{{Request::is('corporate-admin/availability')?'activelist':''}}">
          <a href="{{route('corporate-admin.availability')}}">Performer Availability</a>
        </li>
        <li class="{{Request::is('corporate-admin/performerstatus')?'activelist':''}}">
          <a href="{{route('corporate-admin.performerstatus')}}">Performer Status</a>
        </li>
        <li class="{{Request::is('corporate-admin/helpdesk')?'activelist':''}}">
          <a href="{{route('corporate-admin.helpdesk')}}">Help Desk</a>
        </li>
      </ul>
    </div>